parameters:
    database_driver:   pdo_mysql
    database_host:     66.148.116.121
    database_port:     ~
    database_name:     obj1_001_001
    database_user:     obj1_001_001
    database_password: d8rul3s3!

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIts